#Percentage of original interface brightness to apply.
#Range: 0.0 ~ 1.0
texture_darkness = 0.5
#Specifies gui paths and resources to darken. Use '*' as wildcard char. Directory boundaries will not be crossed. Begin with a namespace or skip namespace to apply to all namespaces. Begin with '!' to exclude matches.
paths = ["textures/gui/*.png", "!minecraft:textures/gui/icons.png", "!minecraft:textures/gui/options_background.png", "textures/gui/container/*.png", "minecraft:textures/gui/container/creative_inventory/*.png", "trinkets:textures/gui/slots/*.png"]
#Print menu type to game chat whenever a new menu screen is opened. Intended for finding menu types to be added to "menu_blacklist".
debug_container_types = false
#Do not add the dark mode toggle buttons to the top of every menu.
hide_ingame_switcher = false
#Exclude certain menus from showing the dark mode switcher. Useful when the box intersects other screen elements.
menu_blacklist = []
#Use a dark theme for the configuration screens.
dark_theme = false
#The minimum brightness value of font while dark mode is enabled.
#Range: 0.0 ~ 1.0
font_brightness = 0.75
#Algorithm selector for darkening interface pixels.
#Allowed Values: GRAYSCALE_AND_HSP, HSP, GRAYSCALE_AND_HSL, HSL, GRAYSCALE_AND_LINEAR, LINEAR
darkening_algorithm = "GRAYSCALE_AND_HSP"

