
["Wolf Dog Utilities"]
	#"Dog" refers to the dog from DoggyTalents.
	#If DoggyTalents is not installed, every config below involving "Dog" will simply have no effect.
	#
	#This allows random wolves who dies in the wild to notify all player and get another chance to be tamed. 
	save_wild_wolf = false
	#This put a limit on how many wolves each player can tame.
	wolf_tame_limit = true
	#This define the limit of how many wolves each player can tame.
	#Range: > 1
	wolf_tame_limit_value = 3
	#This put a limit on how many dogs each player can train.
	dog_train_limit = true
	#This define the limit on how many dogs each player can train.
	#Range: > 1
	dog_train_limit_value = 3
	#Specifies whether wolves of the owner can breed while tame limit is reached.
	wolf_breed_over_limit = false
	#Specifies whether dogs of the owner can breed while train limit is reached.
	dog_breed_over_limit = false
	#This allows player to see how many wolves they got by Shift+RightClicking any wolves with a Bone in hand
	show_wolf_tame_count = true
	#This allows player to see how many wolves they have bred by Shift+RightClicking any wolves with a Poppy in hand
	show_wolf_breed_count = true
	#This allows player to see how many wolves have died by Shift+RightClicking any wolves with an Axe in hand
	show_wolf_death_count = true

