name: Build Modpack
on: [push]

jobs:
  Curseforge-Like:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: vimtor/action-zip@v1
        with:
          files: overrides/ manifest.json modlist.html
          dest: result.zip
