name: Build Modpack
on: [push]

jobs:
  Curseforge-Like:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: mkdir result
      - run: mv overrides/ result/
      - run: mv manifest.json result/
      - run: mv modlist.html result/
      - uses: actions/upload-artifact@v3
        with:
          name: curseforge-like
          path: ${{ github.workspace }}/result
