name: Build Modpack
on: [push]

jobs:
  Curseforge-Like:
    runs-on: ubuntu-latest
    steps:
      - run: wget http://github.com/${{ github.event.repository.full_name }}/archive/${{ github.ref }}.tar.gz
      - run: tar -xvzf $(ls)
      - run: zip -r output.zip $(ls --hide=*.tar.gz)/*
      - uses: actions/upload-artifact@v3
        with:
          name: output
          path: ${{ github.event.repository.name }}-${{ github.ref_name }}/**/*
