name: Build and Release

on:
  push:

env:
  GITHUB_TOKEN: ${{ github.token }}

jobs:
  build:
    name: Format Manifest
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Format manifest.json
      run: jq . manifest.json > manifest.json
    
    - name: Commit files
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "JSON Formatter"
        git add -A
        git commit -m "chore(): Format manifest.json"
        
    - name: Push changes
      uses: ad-m/github-push-action@v0.6.0
      with:
        github_token: ${{ github.token }}
        tags: true